# Generated by Django 3.2.25 on 2024-05-01 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'عنوان ها',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='شرح')),
                ('total_score', models.IntegerField(default=20, verbose_name='بارم')),
                ('participant_score', models.IntegerField(default=0, verbose_name='نمره ی کسب شده')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='شرکت کنندگان')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.topics', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'کوییز',
                'verbose_name_plural': 'کوییز ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='صورت سوال')),
                ('score', models.IntegerField(default=0, verbose_name='بارم')),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150, verbose_name='جواب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='درست/غلط')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'جواب',
                'verbose_name_plural': 'جواب ها',
            },
        ),
    ]
