# Generated by Django 3.2.25 on 2024-05-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20240501_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'موضوع', 'verbose_name_plural': 'موضوعات'},
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='عنوان کوییز'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='عنوان کوییز'),
        ),
    ]
