# Generated by Django 3.2.25 on 2024-05-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='درست پاسخ داده شده/نشده'),
        ),
    ]
