# Generated by Django 3.2.25 on 2024-05-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quiz_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'دانش آموز', 'verbose_name_plural': 'دانش آموزان'},
        ),
    ]
