# Generated by Django 3.2.25 on 2024-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_participants_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='participants',
            name='correct',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Question', verbose_name='جواب های درست'),
        ),
    ]
