# Generated by Django 3.2.25 on 2024-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20240501_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='correct',
        ),
        migrations.AddField(
            model_name='participants',
            name='wrong_answers',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Question', verbose_name='جواب های اشتباه'),
        ),
    ]
