# Generated by Django 3.2.25 on 2024-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20240502_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='پایان یافته/نیافته'),
        ),
    ]
