# Generated by Django 3.2.25 on 2024-05-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_participants_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='wrong_answers',
        ),
    ]
